export const sampleCards = [
  {
    id: 'strike',
    name: 'Strike',
    description: 'Deal 5 damage and begins a Frenzy combo.',
    category: 'Ability',
    rarity: 'Common',
    energyCost: 1,
    cooldown: 0,
    effect: { type: 'damage', magnitude: 5 },
    roleTag: 'DPS',
    synergyTag: 'Frenzy',
    synergyEffect: { type: 'extra_attack', magnitude: 1 },
    isComboStarter: true,
  },
  {
    id: 'heal',
    name: 'Heal',
    description: 'Restore 5 health to an ally.',
    category: 'Ability',
    rarity: 'Common',
    energyCost: 1,
    cooldown: 0,
    effect: { type: 'heal', magnitude: 5 },
    roleTag: 'Healer',
  },
  {
    id: 'inspire',
    name: 'Inspire',
    description: "Boost an ally's stats by 1.",
    category: 'Ability',
    rarity: 'Common',
    energyCost: 1,
    cooldown: 0,
    effect: { type: 'buff', magnitude: 1, target: 'ally' },
    roleTag: 'Support',
  },
  {
    id: 'iron_sword',
    name: 'Iron Sword',
    description: 'Weapon that increases attack by 2.',
    category: 'Equipment',
    rarity: 'Common',
    statModifiers: [{ stat: 'attack', value: 2 }],
    slot: 'Weapon',
  },
  {
    id: 'herb',
    name: 'Medicinal Herb',
    description: 'Ingredient for basic remedies.',
    category: 'Ingredient',
    rarity: 'Common',
    ingredientType: 'Herb',
  },
  {
    id: 'bread',
    name: 'Stale Bread',
    description: 'Slightly restores hunger.',
    category: 'FoodDrink',
    rarity: 'Common',
    restoreHunger: 5,
    restoreThirst: 0,
  },
  {
    id: 'haste_elixir',
    name: 'Haste Elixir',
    description: 'Gain +1 speed for 3 turns.',
    category: 'Elixir',
    rarity: 'Uncommon',
    effects: [{ type: 'speed', magnitude: 1, duration: 3 }],
    duration: 3,
  },
  {
    id: 'campfire',
    name: 'Campfire Kit',
    description: 'Rest to recover 5 health.',
    category: 'Utility',
    rarity: 'Common',
    utilityType: 'Campfire',
    effect: { type: 'rest', magnitude: 5 },
  },
  {
    id: 'mark_target',
    name: 'Mark Target',
    description: 'Debuff an enemy to enable Execute combo.',
    category: 'Ability',
    rarity: 'Common',
    energyCost: 1,
    cooldown: 0,
    effect: { type: 'debuff', magnitude: 1, target: 'enemy' },
    roleTag: 'Support',
    synergyTag: 'Execute',
    isComboStarter: true,
  },
  {
    id: 'shadow_execution',
    name: 'Shadow Execution',
    description: 'Deal 8 damage as the Execute finisher.',
    category: 'Ability',
    rarity: 'Common',
    energyCost: 1,
    cooldown: 0,
    effect: { type: 'damage', magnitude: 8 },
    roleTag: 'DPS',
    synergyTag: 'Execute',
    isComboFinisher: true,
  },
  {
    id: 'fireball',
    name: 'Fireball',
    description: 'Hurl a fiery orb that deals 6 fire damage.',
    category: 'Ability',
    rarity: 'Common',
    energyCost: 1,
    cooldown: 0,
    effect: { type: 'damage', magnitude: 6, element: 'fire' },
    roleTag: 'DPS',
  },
]
