export const sampleCards = [
  {
    id: 'strike',
    name: 'Strike',
    category: 'Ability',
    rarity: 'Common',
    energyCost: 1,
    cooldown: 0,
    effect: { type: 'damage', magnitude: 5 },
    roleTag: 'DPS',
    synergyTag: 'Frenzy',
    synergyEffect: { type: 'extra_attack', magnitude: 1 },
  },
  {
    id: 'heal',
    name: 'Heal',
    category: 'Ability',
    rarity: 'Common',
    energyCost: 1,
    cooldown: 0,
    effect: { type: 'heal', magnitude: 5 },
    roleTag: 'Healer',
  },
  {
    id: 'inspire',
    name: 'Inspire',
    category: 'Ability',
    rarity: 'Common',
    energyCost: 1,
    cooldown: 0,
    effect: { type: 'buff', magnitude: 1, target: 'ally' },
    roleTag: 'Support',
  },
  {
    id: 'iron_sword',
    name: 'Iron Sword',
    category: 'Equipment',
    rarity: 'Common',
    statModifiers: [{ stat: 'attack', value: 2 }],
    slot: 'Weapon',
  },
  {
    id: 'herb',
    name: 'Medicinal Herb',
    category: 'Ingredient',
    rarity: 'Common',
    ingredientType: 'Herb',
  },
  {
    id: 'bread',
    name: 'Stale Bread',
    category: 'FoodDrink',
    rarity: 'Common',
    restoreHunger: 5,
    restoreThirst: 0,
  },
  {
    id: 'haste_elixir',
    name: 'Haste Elixir',
    category: 'Elixir',
    rarity: 'Uncommon',
    effects: [{ type: 'speed', magnitude: 1, duration: 3 }],
    duration: 3,
  },
  {
    id: 'campfire',
    name: 'Campfire Kit',
    category: 'Utility',
    rarity: 'Common',
    utilityType: 'Campfire',
    effect: { type: 'rest', magnitude: 5 },
  },
]
