export const sampleCards = [
  {
    id: 'strike',
    name: 'Strike',
    description: 'Deal 5 damage and begins a Frenzy combo.',
    category: 'Ability',
    rarity: 'Common',
    energyCost: 1,
    cooldown: 0,
    effect: { type: 'damage', magnitude: 5 },
    roleTag: 'DPS',
    synergyTag: 'Frenzy',
    synergyEffect: { type: 'extra_attack', magnitude: 1 },
    isComboStarter: true,
  },
  {
    id: 'heal',
    name: 'Heal',
    description: 'Restore 5 health to an ally.',
    category: 'Ability',
    rarity: 'Common',
    energyCost: 1,
    cooldown: 0,
    effect: { type: 'heal', magnitude: 5 },
    roleTag: 'Healer',
  },
  {
    id: 'inspire',
    name: 'Inspire',
    description: "Boost an ally's stats by 1.",
    category: 'Ability',
    rarity: 'Common',
    energyCost: 1,
    cooldown: 0,
    effect: { type: 'buff', magnitude: 1, target: 'ally' },
    roleTag: 'Support',
  },
  {
    id: 'iron_sword',
    name: 'Iron Sword',
    description: 'Weapon that increases attack by 2.',
    category: 'Equipment',
    rarity: 'Common',
    statModifiers: [{ stat: 'attack', value: 2 }],
    slot: 'Weapon',
  },
  {
    id: 'herb',
    name: 'Medicinal Herb',
    description: 'Ingredient for basic remedies.',
    category: 'Ingredient',
    rarity: 'Common',
    ingredientType: 'Herb',
  },
  {
    id: 'bread',
    name: 'Stale Bread',
    description: 'Slightly restores hunger.',
    category: 'FoodDrink',
    rarity: 'Common',
    restoreHunger: 5,
    restoreThirst: 0,
  },
  {
    id: 'haste_elixir',
    name: 'Haste Elixir',
    description: 'Gain +1 speed for 3 turns.',
    category: 'Elixir',
    rarity: 'Uncommon',
    effects: [{ type: 'speed', magnitude: 1, duration: 3 }],
    duration: 3,
  },
  {
    id: 'campfire',
    name: 'Campfire Kit',
    description: 'Rest to recover 5 health.',
    category: 'Utility',
    rarity: 'Common',
    utilityType: 'Campfire',
    effect: { type: 'rest', magnitude: 5 },
  },
  {
    id: 'mark_target',
    name: 'Mark Target',
    description: 'Debuff an enemy to enable Execute combo.',
    category: 'Ability',
    rarity: 'Common',
    energyCost: 1,
    cooldown: 0,
    effect: { type: 'debuff', magnitude: 1, target: 'enemy' },
    roleTag: 'Support',
    synergyTag: 'Execute',
    isComboStarter: true,
  },
  {
    id: 'shadow_execution',
    name: 'Shadow Execution',
    description: 'Deal 8 damage as the Execute finisher.',
    category: 'Ability',
    rarity: 'Common',
    energyCost: 1,
    cooldown: 0,
    effect: { type: 'damage', magnitude: 8 },
    roleTag: 'DPS',
    synergyTag: 'Execute',
    isComboFinisher: true,
  },
  {
    id: 'fireball',
    name: 'Fireball',
    description: 'Hurl a fiery orb that deals 6 fire damage.',
    category: 'Ability',
    rarity: 'Common',
    energyCost: 1,
    cooldown: 0,
    effect: { type: 'damage', magnitude: 6, element: 'fire' },
    roleTag: 'DPS',
  },
  {
    id: 'shield_wall',
    name: 'Shield Wall',
    description: 'Raise a barrier granting 3 defense for 2 turns.',
    category: 'Ability',
    rarity: 'Common',
    energyCost: 1,
    cooldown: 1,
    effect: { type: 'buff', magnitude: 3, duration: 2 },
    roleTag: 'Tank',
    classRestriction: 'Guardian',
  },
  {
    id: 'taunt',
    name: 'Taunt',
    description: 'Force an enemy to target you next turn.',
    category: 'Ability',
    rarity: 'Common',
    energyCost: 1,
    cooldown: 1,
    effect: { type: 'debuff', magnitude: 1, target: 'enemy' },
    roleTag: 'Tank',
    classRestriction: 'Guardian',
  },
  {
    id: 'power_strike',
    name: 'Power Strike',
    description: 'Deliver a heavy blow dealing 7 damage.',
    category: 'Ability',
    rarity: 'Common',
    energyCost: 1,
    cooldown: 0,
    effect: { type: 'damage', magnitude: 7 },
    roleTag: 'Tank',
    classRestriction: 'Warrior',
  },
  {
    id: 'battle_cry',
    name: 'Battle Cry',
    description: 'Increase all allies\' attack by 1 for 2 turns.',
    category: 'Ability',
    rarity: 'Common',
    energyCost: 1,
    cooldown: 2,
    effect: { type: 'buff', magnitude: 1, duration: 2, target: 'party' },
    roleTag: 'Tank',
    classRestriction: 'Warrior',
  },
  {
    id: 'rune_slam',
    name: 'Rune Slam',
    description: 'Smash an enemy with rune power for 6 damage.',
    category: 'Ability',
    rarity: 'Common',
    energyCost: 1,
    cooldown: 0,
    effect: { type: 'damage', magnitude: 6 },
    roleTag: 'Tank',
    classRestriction: 'RunestoneSentinel',
  },
  {
    id: 'stone_guard',
    name: 'Stone Guard',
    description: 'Gain 2 defense for 3 turns.',
    category: 'Ability',
    rarity: 'Common',
    energyCost: 1,
    cooldown: 1,
    effect: { type: 'buff', magnitude: 2, duration: 3 },
    roleTag: 'Tank',
    classRestriction: 'RunestoneSentinel',
  },
  {
    id: 'holy_light',
    name: 'Holy Light',
    description: 'Restore 6 health to an ally.',
    category: 'Ability',
    rarity: 'Common',
    energyCost: 1,
    cooldown: 0,
    effect: { type: 'heal', magnitude: 6 },
    roleTag: 'Healer',
    classRestriction: 'Cleric',
  },
  {
    id: 'smite',
    name: 'Smite',
    description: 'Deal 4 holy damage to an enemy.',
    category: 'Ability',
    rarity: 'Common',
    energyCost: 1,
    cooldown: 0,
    effect: { type: 'damage', magnitude: 4, element: 'holy' },
    roleTag: 'Healer',
    classRestriction: 'Cleric',
  },
  {
    id: 'healing_herbs',
    name: 'Healing Herbs',
    description: 'Apply herbal remedies to heal 5 health.',
    category: 'Ability',
    rarity: 'Common',
    energyCost: 1,
    cooldown: 0,
    effect: { type: 'heal', magnitude: 5 },
    roleTag: 'Healer',
    classRestriction: 'Herbalist',
  },
  {
    id: 'toxic_spores',
    name: 'Toxic Spores',
    description: 'Release spores that deal 3 damage for 2 turns.',
    category: 'Ability',
    rarity: 'Common',
    energyCost: 1,
    cooldown: 1,
    effect: { type: 'damage', magnitude: 3, duration: 2, element: 'poison' },
    roleTag: 'Healer',
    classRestriction: 'Herbalist',
  },
  {
    id: 'blood_leech',
    name: 'Blood Leech',
    description: 'Drain 4 health from an enemy and heal yourself.',
    category: 'Ability',
    rarity: 'Common',
    energyCost: 1,
    cooldown: 0,
    effect: { type: 'damage', magnitude: 4 },
    roleTag: 'Healer',
    classRestriction: 'Bloodweaver',
    synergyTag: 'Drain',
  },
  {
    id: 'sanguine_gift',
    name: 'Sanguine Gift',
    description: 'Sacrifice 2 health to heal an ally for 6.',
    category: 'Ability',
    rarity: 'Common',
    energyCost: 1,
    cooldown: 1,
    effect: { type: 'heal', magnitude: 6 },
    roleTag: 'Healer',
    classRestriction: 'Bloodweaver',
  },
  {
    id: 'song_of_swiftness',
    name: 'Song of Swiftness',
    description: 'Grant all allies +1 speed for 2 turns.',
    category: 'Ability',
    rarity: 'Common',
    energyCost: 1,
    cooldown: 1,
    effect: { type: 'buff', magnitude: 1, duration: 2, target: 'party' },
    roleTag: 'Support',
    classRestriction: 'Bard',
  },
  {
    id: 'time_warp',
    name: 'Time Warp',
    description: 'Reduce an ally\'s cooldowns by 1 turn.',
    category: 'Ability',
    rarity: 'Common',
    energyCost: 1,
    cooldown: 2,
    effect: { type: 'buff', magnitude: 1, target: 'ally' },
    roleTag: 'Support',
    classRestriction: 'Chronomancer',
  },
  {
    id: 'temporal_strike',
    name: 'Temporal Strike',
    description: 'Deal 5 damage and slow the enemy.',
    category: 'Ability',
    rarity: 'Common',
    energyCost: 1,
    cooldown: 0,
    effect: { type: 'damage', magnitude: 5 },
    roleTag: 'Support',
    classRestriction: 'Chronomancer',
  },
  {
    id: 'totem_of_vitality',
    name: 'Totem of Vitality',
    description: 'Place a totem that heals allies for 2 each turn.',
    category: 'Ability',
    rarity: 'Common',
    energyCost: 1,
    cooldown: 2,
    effect: { type: 'heal', magnitude: 2, duration: 3 },
    roleTag: 'Support',
    classRestriction: 'TotemWarden',
  },
  {
    id: 'totem_of_fury',
    name: 'Totem of Fury',
    description: 'Place a totem that increases ally damage by 1.',
    category: 'Ability',
    rarity: 'Common',
    energyCost: 1,
    cooldown: 2,
    effect: { type: 'buff', magnitude: 1, duration: 3 },
    roleTag: 'Support',
    classRestriction: 'TotemWarden',
  },
  {
    id: 'quick_slash',
    name: 'Quick Slash',
    description: 'Swiftly strike for 4 damage.',
    category: 'Ability',
    rarity: 'Common',
    energyCost: 1,
    cooldown: 0,
    effect: { type: 'damage', magnitude: 4 },
    roleTag: 'DPS',
    classRestriction: 'Blademaster',
  },
  {
    id: 'blade_fury',
    name: 'Blade Fury',
    description: 'Unleash multiple strikes dealing 2 damage twice.',
    category: 'Ability',
    rarity: 'Common',
    energyCost: 1,
    cooldown: 1,
    effect: { type: 'damage', magnitude: 4 },
    roleTag: 'DPS',
    classRestriction: 'Blademaster',
  },
  {
    id: 'arcane_bolt',
    name: 'Arcane Bolt',
    description: 'Deal 5 arcane damage to an enemy.',
    category: 'Ability',
    rarity: 'Common',
    energyCost: 1,
    cooldown: 0,
    effect: { type: 'damage', magnitude: 5, element: 'arcane' },
    roleTag: 'DPS',
    classRestriction: 'Wizard',
  },
  {
    id: 'mana_shield',
    name: 'Mana Shield',
    description: 'Gain a shield absorbing 4 damage for 2 turns.',
    category: 'Ability',
    rarity: 'Common',
    energyCost: 1,
    cooldown: 1,
    effect: { type: 'buff', magnitude: 4, duration: 2 },
    roleTag: 'DPS',
    classRestriction: 'Wizard',
  },
  {
    id: 'backstab',
    name: 'Backstab',
    description: 'Deal 6 damage. Deals double if used from stealth.',
    category: 'Ability',
    rarity: 'Common',
    energyCost: 1,
    cooldown: 0,
    effect: { type: 'damage', magnitude: 6 },
    roleTag: 'DPS',
    classRestriction: 'Shadowblade',
  },
  {
    id: 'smoke_bomb',
    name: 'Smoke Bomb',
    description: 'Gain stealth for 1 turn and reduce enemy accuracy.',
    category: 'Ability',
    rarity: 'Common',
    energyCost: 1,
    cooldown: 1,
    effect: { type: 'buff', magnitude: 1, duration: 1 },
    roleTag: 'DPS',
    classRestriction: 'Shadowblade',
  },
  {
    id: 'arrow_shot',
    name: 'Arrow Shot',
    description: 'Shoot an arrow dealing 5 damage.',
    category: 'Ability',
    rarity: 'Common',
    energyCost: 1,
    cooldown: 0,
    effect: { type: 'damage', magnitude: 5 },
    roleTag: 'DPS',
    classRestriction: 'Ranger',
  },
  {
    id: 'entangling_trap',
    name: 'Entangling Trap',
    description: 'Root an enemy for 1 turn and deal 2 damage.',
    category: 'Ability',
    rarity: 'Common',
    energyCost: 1,
    cooldown: 1,
    effect: { type: 'debuff', magnitude: 1, duration: 1 },
    roleTag: 'DPS',
    classRestriction: 'Ranger',
  },
  {
    id: 'flame_shield',
    name: 'Flame Shield',
    description: 'Surround yourself with flames reducing damage by 2.',
    category: 'Ability',
    rarity: 'Common',
    energyCost: 1,
    cooldown: 1,
    effect: { type: 'buff', magnitude: 2, duration: 2 },
    roleTag: 'DPS',
    classRestriction: 'Pyromancer',
  },
]
