const clericPortrait = new URL('../images/cleric-portrait.png', import.meta.url).href
const defaultPortrait = new URL('../images/default-portrait.png', import.meta.url).href

export const Role = {
  Tank: 'Tank',
  Healer: 'Healer',
  Support: 'Support',
  DPS: 'DPS',
}

export const classes = [
  {
    id: 'Guardian',
    name: 'Guardian',
    description: 'Sturdy protector that draws enemy attacks and shields allies.',
    role: Role.Tank,
    allowedCards: [
      'fortified_stance',
      'intervene',
      'guards_challenge',
      'bulwark',
    ],
    portrait: defaultPortrait,
  },
  {
    id: 'Warrior',
    name: 'Warrior',
    description: 'Aggressive melee combatant excelling at frontline skirmishes.',
    role: Role.Tank,
    allowedCards: ['power_strike', 'battle_cry'],
    portrait: defaultPortrait,
  },
  {
    id: 'RunestoneSentinel',
    name: 'Runestone Sentinel',
    description: 'Tank that channels rune magic to harden defenses.',
    role: Role.Tank,
    allowedCards: ['rune_slam', 'stone_guard'],
    portrait: defaultPortrait,
  },
  {
    id: 'Cleric',
    name: 'Cleric',
    description: 'Devout healer who mends wounds with holy magic.',
    role: Role.Healer,
    allowedCards: ['holy_light', 'smite'],
    portrait: clericPortrait,
  },
  {
    id: 'Herbalist',
    name: 'Herbalist',
    description: 'Nature healer brewing restorative and toxic concoctions.',
    role: Role.Healer,
    allowedCards: ['healing_herbs', 'toxic_spores'],
    portrait: defaultPortrait,
  },
  {
    id: 'Bloodweaver',
    name: 'Bloodweaver',
    description: 'Mystic manipulating life essence to heal or harm.',
    role: Role.Healer,
    allowedCards: ['blood_leech', 'sanguine_gift'],
    portrait: defaultPortrait,
  },
  {
    id: 'Bard',
    name: 'Bard',
    description: 'Inspirational performer empowering allies through song.',
    role: Role.Support,
    allowedCards: ['inspire', 'song_of_swiftness'],
    portrait: defaultPortrait,
  },
  {
    id: 'Chronomancer',
    name: 'Chronomancer',
    description: 'Temporal magician bending time to aid the party.',
    role: Role.Support,
    allowedCards: ['time_warp', 'temporal_strike'],
    portrait: defaultPortrait,
  },
  {
    id: 'TotemWarden',
    name: 'Totem Warden',
    description: 'Places totems that bolster friends or weaken foes.',
    role: Role.Support,
    allowedCards: ['totem_of_vitality', 'totem_of_fury', 'totem_of_stoneskin', 'totem_recall'],
    portrait: defaultPortrait,
  },
  {
    id: 'Blademaster',
    name: 'Blademaster',
    description: 'Master of blades delivering relentless attacks.',
    role: Role.DPS,
    allowedCards: ['quick_slash', 'blade_fury'],
    portrait: defaultPortrait,
  },
  {
    id: 'Wizard',
    name: 'Wizard',
    description: 'Arcane caster wielding destructive and protective spells.',
    role: Role.DPS,
    allowedCards: ['arcane_bolt', 'mana_shield'],
    portrait: defaultPortrait,
  },
  {
    id: 'Shadowblade',
    name: 'Shadowblade',
    description: 'Stealthy assassin striking from the darkness.',
    role: Role.DPS,
    allowedCards: ['backstab', 'smoke_bomb'],
    portrait: defaultPortrait,
  },
  {
    id: 'Ranger',
    name: 'Ranger',
    description: 'Expert archer adept at controlling the battlefield.',
    role: Role.DPS,
    allowedCards: ['arrow_shot', 'entangling_trap'],
    portrait: defaultPortrait,
  },
  {
    id: 'Pyromancer',
    name: 'Pyromancer',
    description: 'Sorcerer harnessing fire for offense and defense.',
    role: Role.DPS,
    allowedCards: ['fireball', 'flame_shield'],
    portrait: defaultPortrait,
  },
]
