import { enemyCards } from './enemyCards.js'

export const enemies = [
  {
    id: 'blood_witch',
    name: 'Blood Witch',
    archetype: 'Blood Witch',
    stats: { hp: 22, energy: 3, speed: 2 },
    deck: enemyCards.filter(c => c.archetype === 'Blood Witch'),
    aiProfile: { behavior: 'aggressive', aggressiveness: 0.7, enableComboAwareness: true, comboWindowTurns: 2, prefersFinisherChains: true },
  },
  {
    id: 'brute',
    name: 'Brute',
    archetype: 'Brute',
    stats: { hp: 28, energy: 2, speed: 1 },
    deck: enemyCards.filter(c => c.archetype === 'Brute'),
    aiProfile: { behavior: 'aggressive', aggressiveness: 0.8, enableComboAwareness: true, comboWindowTurns: 2, prefersFinisherChains: true },
  },
  {
    id: 'frost_revenant',
    name: 'Frost Revenant',
    archetype: 'Frost Revenant',
    stats: { hp: 24, energy: 2, speed: 2 },
    deck: enemyCards.filter(c => c.archetype === 'Frost Revenant'),
    aiProfile: { behavior: 'control', aggressiveness: 0.6, enableComboAwareness: true, comboWindowTurns: 2, prefersFinisherChains: false },
  },
  {
    id: 'grave_titan',
    name: 'Grave Titan',
    archetype: 'Grave Titan',
    stats: { hp: 35, energy: 2, speed: 1 },
    deck: enemyCards.filter(c => c.archetype === 'Grave Titan'),
    aiProfile: { behavior: 'tank', aggressiveness: 0.5, enableComboAwareness: true, comboWindowTurns: 2, prefersFinisherChains: false },
  },
  {
    id: 'infernal_beast',
    name: 'Infernal Beast',
    archetype: 'Infernal Beast',
    stats: { hp: 26, energy: 2, speed: 2 },
    deck: enemyCards.filter(c => c.archetype === 'Infernal Beast'),
    aiProfile: { behavior: 'aggressive', aggressiveness: 0.9, enableComboAwareness: true, comboWindowTurns: 2, prefersFinisherChains: true },
  },
  {
    id: 'necromancer',
    name: 'Necromancer',
    archetype: 'Necromancer',
    stats: { hp: 20, energy: 3, speed: 1 },
    deck: enemyCards.filter(c => c.archetype === 'Necromancer'),
    aiProfile: { behavior: 'summoner', aggressiveness: 0.6, enableComboAwareness: true, comboWindowTurns: 2, prefersFinisherChains: false },
  },
  {
    id: 'plague_bringer',
    name: 'Plague Bringer',
    archetype: 'Plague Bringer',
    stats: { hp: 24, energy: 2, speed: 1 },
    deck: enemyCards.filter(c => c.archetype === 'Plague Bringer'),
    aiProfile: { behavior: 'debuff', aggressiveness: 0.7, enableComboAwareness: true, comboWindowTurns: 2, prefersFinisherChains: false },
  },
  {
    id: 'shadowfiend',
    name: 'Shadowfiend',
    archetype: 'Shadowfiend',
    stats: { hp: 22, energy: 2, speed: 3 },
    deck: enemyCards.filter(c => c.archetype === 'Shadowfiend'),
    aiProfile: { behavior: 'assassin', aggressiveness: 0.8, enableComboAwareness: true, comboWindowTurns: 2, prefersFinisherChains: true },
  },
  {
    id: 'storm_serpent',
    name: 'Storm Serpent',
    archetype: 'Storm Serpent',
    stats: { hp: 25, energy: 2, speed: 3 },
    deck: enemyCards.filter(c => c.archetype === 'Storm Serpent'),
    aiProfile: { behavior: 'aggressive', aggressiveness: 0.8, enableComboAwareness: true, comboWindowTurns: 2, prefersFinisherChains: true },
  },
  {
    id: 'venomspawn',
    name: 'Venomspawn',
    archetype: 'Venomspawn',
    stats: { hp: 23, energy: 2, speed: 2 },
    deck: enemyCards.filter(c => c.archetype === 'Venomspawn'),
    aiProfile: { behavior: 'controller', aggressiveness: 0.7, enableComboAwareness: true, comboWindowTurns: 2, prefersFinisherChains: false },
  },
  {
    id: 'void_horror',
    name: 'Void Horror',
    archetype: 'Void Horror',
    stats: { hp: 30, energy: 3, speed: 2 },
    deck: enemyCards.filter(c => c.archetype === 'Void Horror'),
    aiProfile: { behavior: 'disruptor', aggressiveness: 0.7, enableComboAwareness: true, comboWindowTurns: 2, prefersFinisherChains: false },
  },
]
