export const enemyCards = [
  // Blood Witch cards
  {
    id: 'blood_boil',
    name: 'Blood Boil',
    archetype: 'Blood Witch',
    cost: 1,
    target: 'Enemy',
    duration: 'Instant',
    notes: '',
    effects: [
      { type: 'DEAL_DAMAGE', target: 'SINGLE_ENEMY', amount: 2, damageType: 'Dark' },
      { type: 'HEAL', target: 'SELF', amount: 2, condition: 'if cursed' },
    ],
  },
  {
    id: 'hex_of_weakness',
    name: 'Hex of Weakness',
    archetype: 'Blood Witch',
    cost: 1,
    target: 'Enemy',
    duration: '2 turns',
    notes: '',
    effects: [
      { type: 'MODIFY_STAT', target: 'SINGLE_ENEMY', stat: 'ATK', amount: -2, duration: 2 },
      { type: 'MODIFY_STAT', target: 'SINGLE_ENEMY', stat: 'DEF', amount: -2, duration: 2 },
    ],
  },
  {
    id: 'blood_pact',
    name: 'Blood Pact',
    archetype: 'Blood Witch',
    cost: 1,
    target: 'Ally',
    duration: 'Instant',
    notes: '',
    effects: [
      { type: 'SELF_DAMAGE', target: 'SELF', amount: 2 },
      { type: 'HEAL', target: 'ALLY', amount: 4 },
    ],
  },
  {
    id: 'vile_mending',
    name: 'Vile Mending',
    archetype: 'Blood Witch',
    cost: 1,
    target: 'Self',
    duration: 'Instant',
    notes: '',
    effects: [
      { type: 'REMOVE_STATUS', target: 'SELF', status: 'Curse' },
      { type: 'HEAL', target: 'SELF', amount: 4 },
    ],
  },
  {
    id: 'dark_benediction',
    name: 'Dark Benediction',
    archetype: 'Blood Witch',
    cost: 2,
    target: 'All Allies',
    duration: '2 turns',
    notes: '',
    effects: [
      { type: 'MODIFY_STAT', target: 'ALL_ALLIES', stat: 'damage', amount: 1, duration: 2 },
      { type: 'MODIFY_STAT', target: 'ALL_ALLIES', stat: 'damage_taken', amount: 1, duration: 2 },
    ],
  },

  // Brute cards
  {
    id: 'crushing_blow',
    name: 'Crushing Blow',
    archetype: 'Brute',
    cost: 1,
    target: 'Enemy',
    duration: 'Instant',
    notes: '',
    effects: [
      { type: 'DEAL_DAMAGE', target: 'SINGLE_ENEMY', amount: 4 },
    ],
  },
  {
    id: 'slam',
    name: 'Slam',
    archetype: 'Brute',
    cost: 2,
    target: 'Enemy',
    duration: '1 turn',
    notes: '',
    effects: [
      { type: 'DEAL_DAMAGE', target: 'SINGLE_ENEMY', amount: 2 },
      { type: 'APPLY_STATUS', target: 'SINGLE_ENEMY', status: 'Stun', duration: 1 },
    ],
  },
  {
    id: 'armor_break',
    name: 'Armor Break',
    archetype: 'Brute',
    cost: 1,
    target: 'Enemy',
    duration: '2 turns',
    notes: '',
    effects: [
      { type: 'DEAL_DAMAGE', target: 'SINGLE_ENEMY', amount: 2 },
      { type: 'REMOVE_SHIELD', target: 'SINGLE_ENEMY' },
      { type: 'MODIFY_STAT', target: 'SINGLE_ENEMY', stat: 'DEF', amount: -2, duration: 2 },
    ],
  },
  {
    id: 'war_shout',
    name: 'War Shout',
    archetype: 'Brute',
    cost: 1,
    target: 'Self',
    duration: '1 turn',
    notes: '',
    effects: [
      { type: 'APPLY_STATUS', target: 'ALL_ENEMIES', status: 'Taunt', duration: 1 },
      { type: 'MODIFY_STAT', target: 'SELF', stat: 'DEF', amount: 2, duration: 1 },
    ],
  },
  {
    id: 'juggernaut_rush',
    name: 'Juggernaut Rush',
    archetype: 'Brute',
    cost: 2,
    target: 'All Enemies/Self',
    duration: 'Instant',
    notes: '',
    effects: [
      { type: 'DEAL_DAMAGE', target: 'ALL_ENEMIES', amount: 2 },
      { type: 'GAIN_SHIELD', target: 'SELF', amount: 5 },
    ],
  },

  // Frost Revenant cards
  {
    id: 'frostbolt',
    name: 'Frostbolt',
    archetype: 'Frost Revenant',
    cost: 1,
    target: 'Enemy',
    duration: '2 turns',
    notes: '',
    effects: [
      { type: 'DEAL_DAMAGE', target: 'SINGLE_ENEMY', amount: 2, damageType: 'Cold' },
      { type: 'APPLY_STATUS', target: 'SINGLE_ENEMY', status: 'Slow', duration: 2 },
    ],
  },
  {
    id: 'glacial_chains',
    name: 'Glacial Chains',
    archetype: 'Frost Revenant',
    cost: 1,
    target: 'Enemy',
    duration: '1 turn',
    notes: '',
    effects: [
      { type: 'APPLY_STATUS', target: 'SINGLE_ENEMY', status: 'Root', duration: 1 },
    ],
  },
  {
    id: 'blizzard',
    name: 'Blizzard',
    archetype: 'Frost Revenant',
    cost: 2,
    target: 'All Enemies',
    duration: '1 turn',
    notes: '',
    effects: [
      { type: 'DEAL_DAMAGE', target: 'ALL_ENEMIES', amount: 1, damageType: 'Cold' },
      { type: 'APPLY_STATUS', target: 'ALL_ENEMIES', status: 'Slow', duration: 1 },
    ],
  },
  {
    id: 'ice_shield',
    name: 'Ice Shield',
    archetype: 'Frost Revenant',
    cost: 1,
    target: 'Self',
    duration: '2 turns',
    notes: '',
    effects: [
      { type: 'GAIN_SHIELD', target: 'SELF', amount: 5, duration: 2 },
      { type: 'APPLY_STATUS', target: 'SELF', status: 'Slow Immunity', duration: 2 },
    ],
  },
  {
    id: 'shatter',
    name: 'Shatter',
    archetype: 'Frost Revenant',
    cost: 1,
    target: 'Enemy',
    duration: 'Instant',
    notes: '',
    effects: [
      { type: 'DEAL_DAMAGE', target: 'SINGLE_ENEMY', amount: 4, condition: 'if Slowed or Frozen' },
    ],
  },

  // Grave Titan cards
  {
    id: 'titanic_slam',
    name: 'Titanic Slam',
    archetype: 'Grave Titan',
    cost: 2,
    target: 'Enemy',
    duration: '1 turn',
    notes: '',
    effects: [
      { type: 'DEAL_DAMAGE', target: 'SINGLE_ENEMY', amount: 3 },
      { type: 'APPLY_STATUS', target: 'SINGLE_ENEMY', status: 'Knockback', duration: 1 },
    ],
  },
  {
    id: 'bone_plating',
    name: 'Bone Plating',
    archetype: 'Grave Titan',
    cost: 1,
    target: 'Self',
    duration: '2 turns',
    notes: '',
    effects: [
      { type: 'GAIN_SHIELD', target: 'SELF', amount: 8, duration: 2 },
    ],
  },
  {
    id: 'earthquake',
    name: 'Earthquake',
    archetype: 'Grave Titan',
    cost: 2,
    target: 'All Enemies',
    duration: '1 turn',
    notes: '',
    effects: [
      { type: 'DEAL_DAMAGE', target: 'ALL_ENEMIES', amount: 2 },
      { type: 'MODIFY_STAT', target: 'ALL_ENEMIES', stat: 'initiative', amount: -1, duration: 1 },
    ],
  },
  {
    id: 'siege_step',
    name: 'Siege Step',
    archetype: 'Grave Titan',
    cost: 1,
    target: 'Self',
    duration: '1 turn',
    notes: '',
    effects: [
      { type: 'APPLY_STATUS', target: 'SELF', status: 'Taunt', duration: 1 },
      { type: 'MODIFY_STAT', target: 'SELF', stat: 'next_attack_damage', amount: 2, duration: 1 },
    ],
  },
  {
    id: 'devour',
    name: 'Devour',
    archetype: 'Grave Titan',
    cost: 1,
    target: 'Self',
    duration: 'Instant',
    notes: '',
    effects: [
      { type: 'HEAL', target: 'SELF', amount: 4, condition: 'if below 50% HP' },
    ],
  },

  // Infernal Beast cards
  {
    id: 'inferno_breath',
    name: 'Inferno Breath',
    archetype: 'Infernal Beast',
    cost: 2,
    target: 'All Enemies',
    duration: '2 turns',
    notes: '',
    effects: [
      { type: 'DEAL_DAMAGE', target: 'ALL_ENEMIES', amount: 2, damageType: 'Fire' },
      { type: 'APPLY_STATUS', target: 'ALL_ENEMIES', status: 'Burn', duration: 2 },
    ],
  },
  {
    id: 'rampage',
    name: 'Rampage',
    archetype: 'Infernal Beast',
    cost: 1,
    target: 'Enemy',
    duration: 'Instant',
    notes: '',
    effects: [
      { type: 'DEAL_DAMAGE', target: 'SINGLE_ENEMY', amount: 4 },
      { type: 'SELF_DAMAGE', target: 'SELF', amount: 2 },
    ],
  },
  {
    id: 'flame_shield_enemy',
    name: 'Flame Shield',
    archetype: 'Infernal Beast',
    cost: 1,
    target: 'Self',
    duration: '2 turns',
    notes: '',
    effects: [
      { type: 'GAIN_SHIELD', target: 'SELF', amount: 5, duration: 2 },
      { type: 'REFLECT_DAMAGE', target: 'SELF', amount: 1, damageType: 'Fire', duration: 2 },
    ],
  },
  {
    id: 'wild_roar',
    name: 'Wild Roar',
    archetype: 'Infernal Beast',
    cost: 1,
    target: 'All Enemies/Self',
    duration: '1 turn',
    notes: '',
    effects: [
      { type: 'MODIFY_STAT', target: 'ALL_ENEMIES', stat: 'DEF', amount: -2, duration: 1 },
      { type: 'MODIFY_STAT', target: 'SELF', stat: 'initiative', amount: 1, duration: 1 },
    ],
  },
  {
    id: 'sear_flesh',
    name: 'Sear Flesh',
    archetype: 'Infernal Beast',
    cost: 1,
    target: 'Enemy',
    duration: '2 turns',
    notes: '',
    effects: [
      { type: 'DEAL_DAMAGE', target: 'SINGLE_ENEMY', amount: 2, damageType: 'Fire' },
      { type: 'APPLY_STATUS', target: 'SINGLE_ENEMY', status: 'Heal Block', duration: 2 },
    ],
  },

  // Necromancer cards
  {
    id: 'summon_skeleton',
    name: 'Summon Skeleton',
    archetype: 'Necromancer',
    cost: 2,
    target: 'Self/Field',
    duration: 'Permanent',
    notes: 'Extra attacker',
    effects: [
      { type: 'SUMMON', target: 'FIELD', unit: 'Skeleton Minion' },
    ],
  },
  {
    id: 'fear',
    name: 'Fear',
    archetype: 'Necromancer',
    cost: 2,
    target: 'Enemy',
    duration: '1 turn',
    notes: '',
    effects: [
      { type: 'APPLY_STATUS', target: 'SINGLE_ENEMY', status: 'Skip Turn', duration: 1 },
    ],
  },
  {
    id: 'grave_touch',
    name: 'Grave Touch',
    archetype: 'Necromancer',
    cost: 1,
    target: 'Enemy',
    duration: 'Instant',
    notes: '',
    effects: [
      { type: 'DEAL_DAMAGE', target: 'SINGLE_ENEMY', amount: 2 },
      { type: 'HEAL', target: 'SELF', amount: 2, condition: "if enemy KO'd" },
    ],
  },
  {
    id: 'bone_armor',
    name: 'Bone Armor',
    archetype: 'Necromancer',
    cost: 1,
    target: 'Self',
    duration: '2 turns',
    notes: '',
    effects: [
      { type: 'GAIN_SHIELD', target: 'SELF', amount: 5, duration: 2 },
    ],
  },
  {
    id: 'death_pulse',
    name: 'Death Pulse',
    archetype: 'Necromancer',
    cost: 2,
    target: 'All Enemies',
    duration: '1 turn',
    notes: '',
    effects: [
      { type: 'DEAL_DAMAGE', target: 'ALL_ENEMIES', amount: 2, damageType: 'Dark' },
      { type: 'MODIFY_STAT', target: 'ALL_ENEMIES', stat: 'initiative', amount: -1, duration: 1 },
    ],
  },

  // Plague Bringer cards
  {
    id: 'plague_cloud',
    name: 'Plague Cloud',
    archetype: 'Plague Bringer',
    cost: 2,
    target: 'All Enemies',
    duration: '2 turns',
    notes: '',
    effects: [
      { type: 'DEAL_DAMAGE', target: 'ALL_ENEMIES', amount: 1, damageType: 'Poison' },
      { type: 'MODIFY_STAT', target: 'ALL_ENEMIES', stat: 'healing_received', amount: -50, duration: 2 },
    ],
  },
  {
    id: 'infection',
    name: 'Infection',
    archetype: 'Plague Bringer',
    cost: 1,
    target: 'Enemy',
    duration: '2 turns',
    notes: '',
    effects: [
      { type: 'DEAL_DAMAGE', target: 'SINGLE_ENEMY', amount: 2, damageType: 'Poison' },
      { type: 'APPLY_STATUS', target: 'SINGLE_ENEMY', status: 'Heal Block', duration: 2 },
    ],
  },
  {
    id: 'virulent_burst',
    name: 'Virulent Burst',
    archetype: 'Plague Bringer',
    cost: 1,
    target: 'Enemy',
    duration: 'Instant',
    notes: '',
    effects: [
      { type: 'SPREAD_DEBUFFS', target: 'ALL_ENEMIES' },
    ],
  },
  {
    id: 'rotting_touch',
    name: 'Rotting Touch',
    archetype: 'Plague Bringer',
    cost: 1,
    target: 'Enemy',
    duration: '2 turns',
    notes: '',
    effects: [
      { type: 'DEAL_DAMAGE', target: 'SINGLE_ENEMY', amount: 1 },
      { type: 'APPLY_STATUS', target: 'SINGLE_ENEMY', status: 'Weak', power: 2, duration: 2 },
    ],
  },
  {
    id: 'malignant_aura',
    name: 'Malignant Aura',
    archetype: 'Plague Bringer',
    cost: 2,
    target: 'All Enemies',
    duration: '2 turns',
    notes: '',
    effects: [
      { type: 'DAMAGE_OVER_TIME', target: 'ALL_ENEMIES', amount: 1, duration: 2 },
    ],
  },

  // Shadowfiend cards
  {
    id: 'shadowstep',
    name: 'Shadowstep',
    archetype: 'Shadowfiend',
    cost: 1,
    target: 'Self',
    duration: '1 turn',
    notes: '',
    effects: [
      { type: 'APPLY_STATUS', target: 'SELF', status: 'Untargetable', duration: 1 },
      { type: 'MODIFY_STAT', target: 'SELF', stat: 'crit_chance', amount: 2, duration: 1 },
    ],
  },
  {
    id: 'ambush',
    name: 'Ambush',
    archetype: 'Shadowfiend',
    cost: 2,
    target: 'Enemy',
    duration: 'Instant',
    notes: '',
    effects: [
      { type: 'DEAL_DAMAGE', target: 'SINGLE_ENEMY', amount: 4, bonus: { condition: 'if undetected', amount: 2 } },
    ],
  },
  {
    id: 'eviscerate',
    name: 'Eviscerate',
    archetype: 'Shadowfiend',
    cost: 1,
    target: 'Enemy',
    duration: '2 turns',
    notes: '',
    effects: [
      { type: 'DEAL_DAMAGE', target: 'SINGLE_ENEMY', amount: 2 },
      { type: 'APPLY_STATUS', target: 'SINGLE_ENEMY', status: 'Bleed', power: 1, duration: 2 },
    ],
  },
  {
    id: 'cloak_of_dusk',
    name: 'Cloak of Dusk',
    archetype: 'Shadowfiend',
    cost: 1,
    target: 'Self',
    duration: '2 turns',
    notes: '',
    effects: [
      { type: 'GAIN_SHIELD', target: 'SELF', amount: 5, duration: 2 },
      { type: 'MODIFY_STAT', target: 'SELF', stat: 'dodge', amount: 30, duration: 2 },
    ],
  },
  {
    id: 'mark_for_death',
    name: 'Mark for Death',
    archetype: 'Shadowfiend',
    cost: 1,
    target: 'Enemy',
    duration: '1 turn',
    notes: '',
    effects: [
      { type: 'APPLY_STATUS', target: 'SINGLE_ENEMY', status: 'Marked', power: 2, duration: 1 },
    ],
  },

  // Storm Serpent cards
  {
    id: 'chain_lightning',
    name: 'Chain Lightning',
    archetype: 'Storm Serpent',
    cost: 2,
    target: 'All Enemies',
    duration: '1 turn',
    notes: '',
    effects: [
      { type: 'DEAL_DAMAGE', target: 'ALL_ENEMIES', amount: 2, damageType: 'Lightning' },
      { type: 'APPLY_STATUS', target: 'ALL_ENEMIES', status: 'Shock', duration: 1 },
    ],
  },
  {
    id: 'static_field',
    name: 'Static Field',
    archetype: 'Storm Serpent',
    cost: 1,
    target: 'All Enemies',
    duration: '2 turns',
    notes: '',
    effects: [
      { type: 'DAMAGE_OVER_TIME', target: 'ALL_ENEMIES', amount: 1, duration: 2 },
    ],
  },
  {
    id: 'flash_strike',
    name: 'Flash Strike',
    archetype: 'Storm Serpent',
    cost: 1,
    target: 'Enemy',
    duration: '1 turn',
    notes: '',
    effects: [
      { type: 'DEAL_DAMAGE', target: 'SINGLE_ENEMY', amount: 3 },
      { type: 'MODIFY_STAT', target: 'SELF', stat: 'initiative', amount: 1, duration: 1 },
    ],
  },
  {
    id: 'electric_coil',
    name: 'Electric Coil',
    archetype: 'Storm Serpent',
    cost: 1,
    target: 'Enemy',
    duration: '1 turn',
    notes: '',
    effects: [
      { type: 'APPLY_STATUS', target: 'SINGLE_ENEMY', status: 'Stun', duration: 1 },
    ],
  },
  {
    id: 'storm_surge',
    name: 'Storm Surge',
    archetype: 'Storm Serpent',
    cost: 1,
    target: 'All Allies',
    duration: '1 turn',
    notes: '',
    effects: [
      { type: 'MODIFY_STAT', target: 'ALL_ALLIES', stat: 'initiative', amount: 1, duration: 1 },
    ],
  },

  // Venomspawn cards
  {
    id: 'venomous_strike',
    name: 'Venomous Strike',
    archetype: 'Venomspawn',
    cost: 1,
    target: 'Enemy',
    duration: '2 turns',
    notes: '',
    effects: [
      { type: 'DAMAGE_OVER_TIME', target: 'SINGLE_ENEMY', amount: 1, damageType: 'Poison', duration: 2 },
    ],
  },
  {
    id: 'root_snare',
    name: 'Root Snare',
    archetype: 'Venomspawn',
    cost: 1,
    target: 'Enemy',
    duration: '1 turn',
    notes: '',
    effects: [
      { type: 'APPLY_STATUS', target: 'SINGLE_ENEMY', status: 'Root', duration: 1 },
    ],
  },
  {
    id: 'neurotoxin',
    name: 'Neurotoxin',
    archetype: 'Venomspawn',
    cost: 1,
    target: 'Enemy',
    duration: '2 turns',
    notes: '',
    effects: [
      { type: 'APPLY_STATUS', target: 'SINGLE_ENEMY', status: 'Heal Block', duration: 2 },
    ],
  },
  {
    id: 'acid_spit',
    name: 'Acid Spit',
    archetype: 'Venomspawn',
    cost: 2,
    target: 'All Enemies',
    duration: '1 turn',
    notes: '',
    effects: [
      { type: 'DEAL_DAMAGE', target: 'ALL_ENEMIES', amount: 1, damageType: 'Acid' },
      { type: 'MODIFY_STAT', target: 'ALL_ENEMIES', stat: 'DEF', amount: -2, duration: 1 },
    ],
  },
  {
    id: 'molt',
    name: 'Molt',
    archetype: 'Venomspawn',
    cost: 1,
    target: 'Self',
    duration: 'Instant',
    notes: 'Cleanse',
    effects: [
      { type: 'REMOVE_DEBUFFS', target: 'SELF' },
    ],
  },

  // Void Horror cards
  {
    id: 'reality_tear',
    name: 'Reality Tear',
    archetype: 'Void Horror',
    cost: 1,
    target: 'Enemy',
    duration: 'Instant',
    notes: '',
    effects: [
      { type: 'DEAL_DAMAGE', target: 'SINGLE_ENEMY', amount: 3, damageType: 'Arcane' },
      { type: 'SHUFFLE_DECK', target: 'SINGLE_ENEMY' },
    ],
  },
  {
    id: 'null_pulse',
    name: 'Null Pulse',
    archetype: 'Void Horror',
    cost: 2,
    target: 'All Enemies',
    duration: 'Instant',
    notes: 'Resource drain',
    effects: [
      { type: 'DRAIN_ENERGY', target: 'ALL_ENEMIES', amount: 2 },
    ],
  },
  {
    id: 'warp_echo',
    name: 'Warp Echo',
    archetype: 'Void Horror',
    cost: 1,
    target: 'Enemy',
    duration: 'Instant',
    notes: 'Mimic',
    effects: [
      { type: 'COPY_ABILITY', target: 'SINGLE_ENEMY' },
    ],
  },
  {
    id: 'paranoia',
    name: 'Paranoia',
    archetype: 'Void Horror',
    cost: 1,
    target: 'Enemy',
    duration: '1 turn',
    notes: 'Mind control',
    effects: [
      { type: 'CONFUSE', target: 'SINGLE_ENEMY', duration: 1 },
    ],
  },
  {
    id: 'entropic_field',
    name: 'Entropic Field',
    archetype: 'Void Horror',
    cost: 2,
    target: 'All Enemies',
    duration: 'Instant',
    notes: 'Strip positive effects',
    effects: [
      { type: 'REMOVE_BUFFS', target: 'ALL_ENEMIES' },
    ],
  },
]
