/** @type {import('./DungeonEvent').DungeonEvent[]} */
export const dungeonEvents = [
  {
    id: 'spore-bloom', // ID is present in JS but not in DungeonEvent.ts, will be an extra property
    name: 'Spore Bloom',
    description: 'All combatants suffer 15% miss chance for the first 3 turns.',
    biomeEligibility: ['fungal-depths'],
    effectType: 'missChance',
    effectDetails: { chance: 0.15, turns: 3 },
    duration: 'floor',
  },
  {
    id: 'mana-freeze',
    name: 'Mana Freeze',
    description: 'Energy regeneration is halved.',
    biomeEligibility: ['frozen-bastion'],
    effectType: 'energyRegenPenalty',
    effectDetails: { multiplier: 0.5 },
    duration: 'floor',
  },
  {
    id: 'volcanic-eruption',
    name: 'Volcanic Eruption',
    description: 'A random party member takes 1 damage every 4 turns.',
    biomeEligibility: ['inferno-ruins'],
    effectType: 'periodicDamage',
    effectDetails: { interval: 4, value: 1, target: 'party' },
    duration: 'floor',
  },
  {
    id: 'vine-wrath',
    name: 'Vine Wrath',
    description: 'Increased chance of being rooted.',
    biomeEligibility: ['thornwild-grove'],
    effectType: 'rootChance',
    effectDetails: { chance: 0.2 },
    duration: 'floor',
  },
  {
    id: 'haunting-echoes',
    name: 'Haunting Echoes',
    description: '30% chance for the first card each turn to cast twice.',
    biomeEligibility: ['ashen-necropolis'],
    effectType: 'doubleCastChance',
    effectDetails: { chance: 0.3 },
    duration: 'floor',
  },
  {
    id: 'arcane-overload',
    name: 'Arcane Overload',
    description: 'Abilities cost +1 energy to play.',
    biomeEligibility: ['crystalline-hollow'],
    effectType: 'energyCostIncrease',
    effectDetails: { amount: 1 },
    duration: 'floor',
  },
  {
    id: 'crashing-wave',
    name: 'Crashing Wave',
    description: 'Water surges push combatants, reducing melee accuracy by 10%.',
    biomeEligibility: ['sunken-deep'],
    effectType: 'meleeAccuracyPenalty',
    effectDetails: { value: -0.1 },
    duration: 'floor',
  },
  {
    id: 'whispers-in-the-dark',
    name: 'Whispers in the Dark',
    description: 'Occasionally confuses adventurers into skipping a turn.',
    biomeEligibility: ['obsidian-reach'],
    effectType: 'skipTurnChance',
    effectDetails: { chance: 0.1 },
    duration: 'floor',
  },
]
