name: GDScript Formatting Check

on:
  push:
    paths:
      - '**.gd'
  pull_request:
    paths:
      - '**.gd'

jobs:
  gdformat-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install gdtoolkit
        run: pip install gdtoolkit

      - name: Run gdformat (check mode)
        run: |
          gdformat --check .
